services:
  fuckbug-api:
    container_name: fuckbug-api
    build:
      context: ../..
      dockerfile: ./deployments/development/Dockerfile
    volumes:
      - ../../.:/app
    environment:
      - AIR_WORKSPACE_ROOT=/app
      - GOPATH=/go
    command: air -c .air.toml
    ports:
      - "80:80"
      - "2345:2345"
    networks:
      - fuckbug_network

networks:
  fuckbug_network:
    driver: bridge